#!/usr/bin/python3
import sys
import subprocess
def main():
    try:
        query = sys.argv[1]
    except IndexError:
        print('gv: no argument provided')
        return 1
    for line in sys.stdin.readlines():
        try:
            l = line.strip('\n').split(': ')
            if l[0] == query:
                print(':'.join(l[1:]).strip('\n'))
        except:
            print('error parsing file')
            return 1
    return 0

main()