#!/usr/bin/env bash
paths=$(echo $PATH | tr ":" "\n" | tac)
echo "$PATHCACHE"
if [ "$PATHCACHE" = "" ]; then
  echo "environment variable PATHCACHE not set, please set it!"
  exit 1
fi

for path in $paths
do
ln -s $path/* $PATHCACHE/
done
exit 0
